name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-pre-commit
      cancel-in-progress: true
    - uses: styfle/cancel-workflow-action@0.10.0
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
        with:
          python-version: 3.9
    - uses: pre-commit/action@v3.0.0
    - name: Installing the library
      shell: bash -l {0}
      run: |
        pip install -e .
        sudo wget https://github.com/jgm/pandoc/releases/download/1.16.0.2/pandoc-1.16.0.2-1-amd64.deb
        sudo dpkg -i pandoc-1.16.0.2-1-amd64.deb
        #sudo apt install pandoc
    - name: Running the Sphinx to gh-pages Action
      uses: uibcdf/action-sphinx-docs-to-gh-pages@v1.0-beta.2
      with:
        branch: main
        dir_docs: docs
        sphinxopts: ""
